#!/usr/bin/env perl
use strict;
use warnings;
use JSON::PP qw(decode_json);
use File::Path qw(make_path);

my $api_path = shift @ARGV // 'extension_api.json';
my $out_dir = shift @ARGV // 'src/generated';
make_path($out_dir);

open my $fh, '<', $api_path or die "open $api_path: $!";
my $json = decode_json(do { local $/; <$fh> });

sub zig_string { my ($s)=@_; $s =~ s/\\/\\\\/g; $s =~ s/"/\\"/g; return '"'.$s.'"'; }
sub ident { my ($s)=@_; $s =~ s/[^A-Za-z0-9_]/_/g; $s = '_'.$s if $s =~ /^[0-9]/; return $s; }
sub qident { my ($s)=@_; $s =~ s/\\/\\\\/g; $s =~ s/"/\\"/g; return '@"'.$s.'"'; }
sub enum_name { my ($s)=@_; $s = lc $s; $s =~ s/^array_//; $s =~ s/[^a-z0-9_]/_/g; $s = '_'.$s if $s =~ /^[0-9]/; return $s; }

my %class = map { $_->{name} => 1 } @{$json->{classes}};
my %singleton_by_type = map { $_->{type} => $_->{name} } @{$json->{singletons} || []};
my %builtin_variant = (
  bool => 'c.GDEXTENSION_VARIANT_TYPE_BOOL',
  int => 'c.GDEXTENSION_VARIANT_TYPE_INT',
  float => 'c.GDEXTENSION_VARIANT_TYPE_FLOAT',
  String => 'c.GDEXTENSION_VARIANT_TYPE_STRING',
  StringName => 'c.GDEXTENSION_VARIANT_TYPE_STRING_NAME',
  Vector2 => 'c.GDEXTENSION_VARIANT_TYPE_VECTOR2',
  Vector2i => 'c.GDEXTENSION_VARIANT_TYPE_VECTOR2I',
  Vector3 => 'c.GDEXTENSION_VARIANT_TYPE_VECTOR3',
  Vector3i => 'c.GDEXTENSION_VARIANT_TYPE_VECTOR3I',
  Vector4 => 'c.GDEXTENSION_VARIANT_TYPE_VECTOR4',
  Vector4i => 'c.GDEXTENSION_VARIANT_TYPE_VECTOR4I',
  Color => 'c.GDEXTENSION_VARIANT_TYPE_COLOR',
  Array => 'c.GDEXTENSION_VARIANT_TYPE_ARRAY',
  Dictionary => 'c.GDEXTENSION_VARIANT_TYPE_DICTIONARY',
  PackedVector3Array => 'c.GDEXTENSION_VARIANT_TYPE_PACKED_VECTOR3_ARRAY',
  PackedInt32Array => 'c.GDEXTENSION_VARIANT_TYPE_PACKED_INT32_ARRAY',
);

my %zig_builtin = (
  bool => 'bool', int => 'i64', float => 'f64', String => 'types.String', StringName => 'types.StringName',
  Vector2 => 'types.Vector2', Vector2i => 'types.Vector2i', Vector3 => 'types.Vector3', Vector3i => 'types.Vector3i',
  Vector4 => 'types.Vector4', Vector4i => 'types.Vector4i', Color => 'types.Color', Dictionary => 'types.Dictionary',
  Array => 'collections.Array', PackedVector3Array => 'collections.PackedVector3Array', PackedInt32Array => 'collections.PackedInt32Array',
);

sub type_name { my ($t)=@_; return undef unless defined $t; $t =~ s/^typedarray::/Array/; return $t; }
sub zig_type {
  my ($t)=@_; $t=type_name($t); return undef unless defined $t;
  return $zig_builtin{$t} if exists $zig_builtin{$t};
  return ident($t) if $class{$t};
  return undef;
}
sub storage_type {
  my ($t)=@_; $t=type_name($t);
  return 'u8' if defined($t) && $t eq 'bool';
  return $zig_builtin{$t} if defined($t) && exists $zig_builtin{$t} && $t !~ /^(Array|PackedVector3Array|PackedInt32Array)$/;
  return 'types.Array' if defined($t) && $t eq 'Array';
  return 'types.PackedVector3Array' if defined($t) && $t eq 'PackedVector3Array';
  return 'types.PackedInt32Array' if defined($t) && $t eq 'PackedInt32Array';
  return 'c.GDExtensionObjectPtr' if defined($t) && $class{$t};
  return undef;
}
sub is_complex_return { my ($t)=@_; $t=type_name($t); return defined($t) && ($class{$t} || $t eq 'Array' || $t eq 'Dictionary' || $t eq 'String' || $t eq 'StringName' || $t eq 'PackedVector3Array' || $t eq 'PackedInt32Array'); }
sub wrap_return {
  my ($t, $expr)=@_; $t=type_name($t);
  return "$expr != 0" if $t eq 'bool';
  return ".{ .value = $expr }" if $t eq 'Array' || $t eq 'PackedVector3Array' || $t eq 'PackedInt32Array';
  return ".init($expr)" if $class{$t};
  return $expr;
}
sub wrap_variant_return {
  my ($t, $var)=@_; $t=type_name($t);
  return "$var.toArray()" if $t eq 'Array';
  return "$var.toDictionary()" if $t eq 'Dictionary';
  return "$var.toString()" if $t eq 'String';
  return "$var.toStringName()" if $t eq 'StringName';
  return "$var.toPackedVector3Array()" if $t eq 'PackedVector3Array';
  return "$var.toPackedInt32Array()" if $t eq 'PackedInt32Array';
  return ".init($var.toObjectPtr())" if $class{$t};
  return undef;
}
sub variant_arg_expr {
  my ($t, $name)=@_; $t=type_name($t);
  return "Variant.fromInt($name)" if $t eq 'int';
  return "Variant.fromBool($name)" if $t eq 'bool';
  return "Variant.fromFloat($name)" if $t eq 'float';
  return undef;
}
sub arg_expr {
  my ($t, $name)=@_; $t=type_name($t);
  return "\@intFromBool($name)" if $t eq 'bool';
  return "$name.value" if $t eq 'Array' || $t eq 'PackedVector3Array' || $t eq 'PackedInt32Array';
  return "$name.object.ptr" if $class{$t};
  return $name;
}

open my $out, '>', "$out_dir/classes.zig" or die $!;
print $out "// Generated by tools/generate_bindings.pl from $api_path. Do not edit by hand.\n";
print $out "const c = \@import(\"../c.zig\").c;\nconst api_mod = \@import(\"../api.zig\");\nconst types = \@import(\"../types.zig\");\nconst GodotObject = \@import(\"../object.zig\").Object;\nconst Variant = \@import(\"../variant.zig\").Variant;\nconst collections = \@import(\"../collections.zig\");\n\n";
print $out "fn bind(class_name: [:0]const u8, method_name: [:0]const u8, hash: i64) c.GDExtensionMethodBindPtr { return api_mod.godot.bind(class_name, method_name, hash); }\n\n";

for my $cl (sort { $a->{name} cmp $b->{name} } @{$json->{classes}}) {
  my $cn = ident($cl->{name});
  print $out "pub const $cn = struct {\n";
  print $out "    object: GodotObject,\n";
  print $out "    pub const godot_class_name = " . zig_string($cl->{name}) . ";\n";
  print $out "    pub const godot_parent_class_name = " . zig_string($cl->{inherits}//"") . ";\n";
  print $out "    pub fn init(ptr: c.GDExtensionObjectPtr) $cn { return .{ .object = .init(ptr) }; }\n";
  print $out "    pub fn isNull(self: $cn) bool { return self.object.isNull(); }\n";
  print $out "    pub fn asObject(self: $cn) GodotObject { return self.object; }\n";
  if (exists $singleton_by_type{$cl->{name}}) {
    print $out "    pub fn singleton() $cn { return .init(api_mod.godot.singleton(" . zig_string($singleton_by_type{$cl->{name}}) . ")); }\n";
  }
  print $out "\n";
  my %seen;
  for my $m (@{$cl->{methods} || []}) {
    next if $m->{is_vararg} || $m->{is_static};
    my $mn = $m->{name};
    next if $seen{$mn}++;
    my @args = @{$m->{arguments} || []};
    next if @args > 3;
    my $ret_t = $m->{return_value} ? type_name($m->{return_value}{type}) : undef;
    my $ret_z = defined($ret_t) ? zig_type($ret_t) : 'void';
    next unless defined $ret_z;
    my @arg_z; my @arg_store; my @arg_call;
    my $ok = 1;
    for my $i (0..$#args) {
      my $t = type_name($args[$i]{type});
      my $zt = zig_type($t); my $st = storage_type($t);
      if (!defined($zt) || !defined($st)) { $ok=0; last; }
      push @arg_z, "arg$i: $zt";
      push @arg_store, "        var a$i: $st = " . arg_expr($t, "arg$i") . ";\n";
      push @arg_call, "&a$i";
    }
    next unless $ok;
    if (is_complex_return($ret_t)) {
      my $variant_ok = 1;
      for my $i (0..$#args) {
        if (!defined(variant_arg_expr(type_name($args[$i]{type}), "arg$i"))) { $variant_ok = 0; last; }
      }
      next unless $variant_ok;
    }
    my $params = join(', ', ('self: '.$cn, @arg_z));
    print $out "    pub fn " . qident($mn) . "($params) $ret_z {\n";
    print $out "        const method = bind(godot_class_name, " . zig_string($mn) . ", $m->{hash});\n";
    if (@args) { print $out @arg_store; print $out "        const args = [_]c.GDExtensionConstTypePtr{ " . join(', ', @arg_call) . " };\n        _ = &args;\n"; }
    if ($ret_z eq 'void') {
      print $out "        api_mod.godot.object_method_bind_ptrcall.?(method, self.object.ptr, " . (@args ? "&args" : "null") . ", null);\n";
    } elsif (is_complex_return($ret_t)) {
      my @vargs; my $vok = 1;
      for my $i (0..$#args) { my $ve = variant_arg_expr(type_name($args[$i]{type}), "arg$i"); if (!defined($ve)) { $vok = 0; last; } push @vargs, $ve; }
      if ($vok) {
        for my $i (0..$#vargs) { print $out "        var v$i = $vargs[$i];\n        defer v$i.destroy();\n"; }
        if (@vargs == 0) { print $out "        var ret = self.object.callVariant0(method);\n"; }
        elsif (@vargs == 1) { print $out "        var ret = self.object.callVariant1(method, &v0);\n"; }
        elsif (@vargs == 2) { print $out "        var ret = self.object.callVariant2(method, &v0, &v1);\n"; }
        elsif (@vargs == 3) { print $out "        var ret = self.object.callVariant3(method, &v0, &v1, &v2);\n"; }
        else { $vok = 0; }
        if ($vok) {
          if (type_name($ret_t) ne 'PackedVector3Array' && type_name($ret_t) ne 'PackedInt32Array') { print $out "        defer ret.destroy();\n"; }
          print $out "        return " . wrap_variant_return($ret_t, 'ret') . ";\n";
        }
      }
      if (!$vok) {
        my $st = storage_type($ret_t);
        print $out "        var out: $st = undefined;\n";
        print $out "        api_mod.godot.object_method_bind_ptrcall.?(method, self.object.ptr, " . (@args ? "&args" : "null") . ", \@ptrCast(&out));\n";
        print $out "        return " . wrap_return($ret_t, 'out') . ";\n";
      }
    } else {
      my $st = storage_type($ret_t);
      print $out "        var out: $st = undefined;\n";
      print $out "        api_mod.godot.object_method_bind_ptrcall.?(method, self.object.ptr, " . (@args ? "&args" : "null") . ", \@ptrCast(&out));\n";
      print $out "        return " . wrap_return($ret_t, 'out') . ";\n";
    }
    print $out "    }\n\n";
  }
  print $out "};\n\n";
}
close $out;

open my $idx, '>', "$out_dir/root.zig" or die $!;
print $idx "// Generated by tools/generate_bindings.pl from $api_path.\n";
print $idx "pub const classes = \@import(\"classes.zig\");\n";
close $idx;

print "generated $out_dir/classes.zig\n";
